/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ProtectedImport } from './routes/_protected'
import { Route as IndexImport } from './routes/index'
import { Route as SignupIndexImport } from './routes/sign_up/index'
import { Route as SignupAdditionalInfoImport } from './routes/sign_up/additional-info'
import { Route as SignupAccountInfoImport } from './routes/sign_up/account-info'

// Create Virtual Routes

const LoginLazyImport = createFileRoute('/login')()
const AboutLazyImport = createFileRoute('/about')()
const ProtectedPostsLazyImport = createFileRoute('/_protected/posts')()
const ProtectedActivitiesLazyImport = createFileRoute(
  '/_protected/activities',
)()
const ProtectedPostIdLazyImport = createFileRoute('/_protected/post/$id')()

// Create/Update Routes

const LoginLazyRoute = LoginLazyImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))

const AboutLazyRoute = AboutLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const ProtectedRoute = ProtectedImport.update({
  id: '/_protected',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SignupIndexRoute = SignupIndexImport.update({
  path: '/sign_up/',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedPostsLazyRoute = ProtectedPostsLazyImport.update({
  path: '/posts',
  getParentRoute: () => ProtectedRoute,
} as any).lazy(() =>
  import('./routes/_protected/posts.lazy').then((d) => d.Route),
)

const ProtectedActivitiesLazyRoute = ProtectedActivitiesLazyImport.update({
  path: '/activities',
  getParentRoute: () => ProtectedRoute,
} as any).lazy(() =>
  import('./routes/_protected/activities.lazy').then((d) => d.Route),
)

const SignupAdditionalInfoRoute = SignupAdditionalInfoImport.update({
  path: '/sign_up/additional-info',
  getParentRoute: () => rootRoute,
} as any)

const SignupAccountInfoRoute = SignupAccountInfoImport.update({
  path: '/sign_up/account-info',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedPostIdLazyRoute = ProtectedPostIdLazyImport.update({
  path: '/post/$id',
  getParentRoute: () => ProtectedRoute,
} as any).lazy(() =>
  import('./routes/_protected/post.$id.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_protected': {
      preLoaderRoute: typeof ProtectedImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginLazyImport
      parentRoute: typeof rootRoute
    }
    '/sign_up/account-info': {
      preLoaderRoute: typeof SignupAccountInfoImport
      parentRoute: typeof rootRoute
    }
    '/sign_up/additional-info': {
      preLoaderRoute: typeof SignupAdditionalInfoImport
      parentRoute: typeof rootRoute
    }
    '/_protected/activities': {
      preLoaderRoute: typeof ProtectedActivitiesLazyImport
      parentRoute: typeof ProtectedImport
    }
    '/_protected/posts': {
      preLoaderRoute: typeof ProtectedPostsLazyImport
      parentRoute: typeof ProtectedImport
    }
    '/sign_up/': {
      preLoaderRoute: typeof SignupIndexImport
      parentRoute: typeof rootRoute
    }
    '/_protected/post/$id': {
      preLoaderRoute: typeof ProtectedPostIdLazyImport
      parentRoute: typeof ProtectedImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  ProtectedRoute.addChildren([
    ProtectedActivitiesLazyRoute,
    ProtectedPostsLazyRoute,
    ProtectedPostIdLazyRoute,
  ]),
  AboutLazyRoute,
  LoginLazyRoute,
  SignupAccountInfoRoute,
  SignupAdditionalInfoRoute,
  SignupIndexRoute,
])

/* prettier-ignore-end */
