FROM node:20

WORKDIR /app

COPY package*.json ./
COPY yarn*.lock ./

# RUN yarn install # disabled for now, because it's not necessary for development

# COPY . .

EXPOSE 3000

CMD ["yarn", "start:dev"]